version: "2"
services:
  release:
    build:
      context: .
      dockerfile: infra/dockerfile_builder

#dnsdock:
#    image: tonistiigi/dnsdock
#    volumes:
#        - /var/run/docker.sock:/run/docker.sock
#    ports:
      #        - 172.17.42.1:53:53/udp
